title: gustavoluciano.com.br
email: contato@gustavoluciano.com.br
description: "Meu site pessoal"
baseurl: ""
url: http://gustavoluciano.com.br

#Build settings
highlighter: pygments 
markdown: kramdown
permalink: /:title

exclude: 
  - "node_modules"
  - "gulpfile.js"
  - "package.json"
  - "package-lock.json"
  - "bower.json"
  - "bower_components"
  - "cfg.js"